# Generated by Django 4.0.6 on 2022-08-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_generalinformation_logo2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinformation',
            name='logo2',
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='footer_logo',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
