# Generated by Django 4.0.6 on 2022-08-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_generalinformation_logo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
